# Generated by Django 3.1.5 on 2021-03-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210226_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='is_watchlist',
        ),
    ]
