# Generated by Django 3.1.5 on 2021-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210307_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='user',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='auction_listing',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.Auction_listing'),
        ),
    ]
