# Generated by Django 3.1.5 on 2021-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210309_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
